load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "supervisor_runner",
    srcs = ["supervisor_runner.cc"],
    hdrs = ["supervisor_runner.h"],
    deps = [
        "//cyber",
    ],
)

cpplint()
